name: multiplication_table
description: A learning exercise creating a multiplication table using Dart with Polymer.
dependencies:
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
